language: java

branches:
  only:
    - dev
    - master

jdk: oraclejdk7


notifications:
  email: false


before_install:

  # environment info
  - gradle -v
  - uname -a

  # required libs for android build tools
  # Update a system for ia32 libraries
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi

  # for gradle output style
  - export TERM=dumb

  # newer version of gradle
  - wget http://services.gradle.org/distributions/gradle-1.11-bin.zip
  - unzip -qq gradle-1.11-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.11
  - export PATH=$GRADLE_HOME/bin:$PATH

  # just to test gradle version, against our provided one
  - gradle -v

# Let's try to build...
install: gradle clean build

script: gradle check


