language: android
android:
  components:
    - build-tools-20.0.0

branches:
  only:
    - master
    - dev

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build

script: ./gradlew clean build


