language: android
android:
  components:
    - tools
    - build-tools-19.0.3
    - android-19
    - extra-android-support
    - extra-android-m2repository

branches:
  only:
    - travis

jdk: oraclejdk7

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
install: ./gradlew clean build

script: ./gradlew check


